// Generated by tools/glyph/generate-glyph-artifacts.mjs from contracts/glyph/v1.json and contracts/glyph/fonts/fractonica-hex-v2.json.
// Grammar SHA-256: fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8
// Font SHA-256: b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8
// Combined SHA-256: f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56
// Do not edit by hand.

use super::GlyphPoint;

pub const GRAMMAR_VERSION: &str = "1.0.0";
pub const GEOMETRY_VERSION: &str = "2.1.0";
pub const FONT_ID: &str = "fractonica-hex-v2";
pub const FONT_VERSION: &str = "1.0.0";
pub const GRAMMAR_SHA256: &str = "fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8";
pub const FONT_SHA256: &str = "b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8";
pub const SPEC_SHA256: &str = "f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56";
pub const RADIX: u8 = 8;
pub const MIN_DIGITS: u8 = 3;
pub const MAX_DIGITS: u8 = 8;
pub const DEFAULT_DIGITS: u8 = 5;
pub const STROKE_LEFT: u8 = 1;
pub const STROKE_CENTRE: u8 = 2;
pub const STROKE_RIGHT: u8 = 4;
pub const FONT_UNITS: f32 = 256.0;
pub const FONT_SOCKET_WIDTH: f32 = 16.0;
pub const FONT_CORE_RADIUS: f32 = 41.57;
pub const FONT_INSET_THICKNESS: f32 = 14.0;
pub const FONT_GRID_SIZE: f32 = 8.0;
pub const FONT_PADDING_CELLS: f32 = 2.0;
pub const FONT_LEGACY_OUTER_DEPTH: u8 = 6;
pub const FONT_LEGACY_HOLE_DEPTH: u8 = 6;
pub const MAX_FONT_ARM_POINTS: usize = 8;

pub const FONT_LEGACY_OUTER: [GlyphPoint; 12] = [
    GlyphPoint::new(-8.0, -41.57),
    GlyphPoint::new(8.0, -41.57),
    GlyphPoint::new(32.0, -27.71),
    GlyphPoint::new(40.0, -13.86),
    GlyphPoint::new(40.0, 13.86),
    GlyphPoint::new(32.0, 27.71),
    GlyphPoint::new(8.0, 41.57),
    GlyphPoint::new(-8.0, 41.57),
    GlyphPoint::new(-32.0, 27.71),
    GlyphPoint::new(-40.0, 13.86),
    GlyphPoint::new(-40.0, -13.86),
    GlyphPoint::new(-32.0, -27.71),
];
pub const FONT_LEGACY_HOLE: [GlyphPoint; 7] = [
    GlyphPoint::new(8.0, 0.0),
    GlyphPoint::new(24.0, 0.0),
    GlyphPoint::new(24.0, 13.86),
    GlyphPoint::new(0.0, 27.71),
    GlyphPoint::new(-24.0, 13.86),
    GlyphPoint::new(-24.0, 0.0),
    GlyphPoint::new(-8.0, 0.0),
];
pub const FONT_ARM_POINT_COUNTS: [u8; 8] = [2, 4, 5, 6, 4, 6, 6, 8];
pub const FONT_ARMS: [[GlyphPoint; MAX_FONT_ARM_POINTS]; 8] = [
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-32.0, 41.57),
        GlyphPoint::new(-16.0, 41.57),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-8.0, 96.99),
        GlyphPoint::new(0.0, 110.85),
        GlyphPoint::new(8.0, 96.99),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-40.0, 55.42),
        GlyphPoint::new(-8.0, 110.85),
        GlyphPoint::new(0.0, 96.99),
        GlyphPoint::new(-24.0, 55.42),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(16.0, 41.57),
        GlyphPoint::new(32.0, 41.57),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-40.0, 55.42),
        GlyphPoint::new(40.0, 55.42),
        GlyphPoint::new(32.0, 41.57),
        GlyphPoint::new(-16.0, 41.57),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-8.0, 138.56),
        GlyphPoint::new(40.0, 55.42),
        GlyphPoint::new(32.0, 41.57),
        GlyphPoint::new(8.0, 83.14),
        GlyphPoint::new(8.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
        GlyphPoint::new(0.0, 0.0),
    ],
    [
        GlyphPoint::new(-8.0, 0.0),
        GlyphPoint::new(-40.0, 55.42),
        GlyphPoint::new(0.0, 124.71),
        GlyphPoint::new(40.0, 55.42),
        GlyphPoint::new(32.0, 41.57),
        GlyphPoint::new(0.0, 96.99),
        GlyphPoint::new(-24.0, 55.42),
        GlyphPoint::new(8.0, 0.0),
    ],
];
