// Generated by tools/glyph/generate-glyph-artifacts.mjs from contracts/glyph/v1.json and contracts/glyph/fonts/fractonica-hex-v2.json.
// Grammar SHA-256: fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8
// Font SHA-256: b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8
// Combined SHA-256: f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56
// Do not edit by hand.

export const glyphSpec = {
  grammarVersion: "1.0.0",
  geometryVersion: "2.1.0",
  sourceSha256: "f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56",
  grammarSha256: "fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8",
  fontSha256: "b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8",
  radix: 8,
  digits: {"minimum":3,"maximum":8,"default":5},
  coordinateSystem: {"origin":"glyph centre","x":"right","y":"down","rotation":"clockwise","unit":"font units"},
  strokeBits: [{"id":"left","bit":1,"from":"anchor","to":"left"},{"id":"centre","bit":2,"from":"anchor","to":"apex"},{"id":"right","bit":4,"from":"anchor","to":"right"}],
  lattice: {"anchor":[0,0],"left":[-1,1],"apex":[0,2],"right":[1,1],"meaning":"A digit is the bitwise sum of its enabled anchor-to-vertex connections. Fonts choose the filled outline used to depict each of the eight masks."},
  defaultFont: {"id":"fractonica-hex-v2","version":"1.0.0","geometryVersion":"2.1.0","source":"fonts/fractonica-hex-v2.json"},
} as const;

export const defaultGlyphFont = {"id":"fractonica-hex-v2","name":"Hex octal glyph font v2","fontVersion":"1.0.0","geometryVersion":"2.1.0","grammarVersion":"1.0.0","sourceSha256":"f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56","units":256,"armsCoordinateMode":"socket","core":{"socketWidth":16,"coreRadius":41.57,"insetThickness":14,"legacyExactOuter":{"depth":6,"points":[[-8,-41.57],[8,-41.57],[32,-27.71],[40,-13.86],[40,13.86],[32,27.71],[8,41.57],[-8,41.57],[-32,27.71],[-40,13.86],[-40,-13.86],[-32,-27.71]]},"legacyExactHole":{"depth":6,"points":[[8,0],[24,0],[24,13.86],[0,27.71],[-24,13.86],[-24,0],[-8,0]]}},"renderer":{"gridSize":8,"paddingCells":2},"arms":[{"digit":0,"points":[[-8,0],[8,0]]},{"digit":1,"points":[[-8,0],[-32,41.57],[-16,41.57],[8,0]]},{"digit":2,"points":[[-8,0],[-8,96.99],[0,110.85],[8,96.99],[8,0]]},{"digit":3,"points":[[-8,0],[-40,55.42],[-8,110.85],[0,96.99],[-24,55.42],[8,0]]},{"digit":4,"points":[[-8,0],[16,41.57],[32,41.57],[8,0]]},{"digit":5,"points":[[-8,0],[-40,55.42],[40,55.42],[32,41.57],[-16,41.57],[8,0]]},{"digit":6,"points":[[-8,0],[-8,138.56],[40,55.42],[32,41.57],[8,83.14],[8,0]]},{"digit":7,"points":[[-8,0],[-40,55.42],[0,124.71],[40,55.42],[32,41.57],[0,96.99],[-24,55.42],[8,0]]}]} as const;

export type GlyphSpec = typeof glyphSpec;
export type DefaultGlyphFont = typeof defaultGlyphFont;
