/* Generated by tools/glyph/generate-glyph-artifacts.mjs from contracts/glyph/v1.json and contracts/glyph/fonts/fractonica-hex-v2.json.
 * Grammar SHA-256: fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8
 * Font SHA-256: b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8
 * Combined SHA-256: f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56
 * Do not edit by hand. */

#ifndef FRACTONICA_EMBEDDED_GLYPH_SPEC_GENERATED_H
#define FRACTONICA_EMBEDDED_GLYPH_SPEC_GENERATED_H

#include <stdint.h>

#define FRACTONICA_GLYPH_GRAMMAR_VERSION "1.0.0"
#define FRACTONICA_GLYPH_GEOMETRY_VERSION "2.1.0"
#define FRACTONICA_GLYPH_FONT_ID "fractonica-hex-v2"
#define FRACTONICA_GLYPH_FONT_VERSION "1.0.0"
#define FRACTONICA_GLYPH_GRAMMAR_SHA256 "fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8"
#define FRACTONICA_GLYPH_FONT_SHA256 "b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8"
#define FRACTONICA_GLYPH_SPEC_SHA256 "f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56"
#define FRACTONICA_GLYPH_SPEC_RADIX 8u
#define FRACTONICA_GLYPH_SPEC_MIN_DIGITS 3u
#define FRACTONICA_GLYPH_SPEC_MAX_DIGITS 8u
#define FRACTONICA_GLYPH_SPEC_DEFAULT_DIGITS 5u
#define FRACTONICA_GLYPH_SPEC_STROKE_LEFT 0x1u
#define FRACTONICA_GLYPH_SPEC_STROKE_CENTRE 0x2u
#define FRACTONICA_GLYPH_SPEC_STROKE_RIGHT 0x4u
#define FRACTONICA_GLYPH_FONT_UNITS 256.0f
#define FRACTONICA_GLYPH_FONT_SOCKET_WIDTH 16.0f
#define FRACTONICA_GLYPH_FONT_CORE_RADIUS 41.57f
#define FRACTONICA_GLYPH_FONT_INSET_THICKNESS 14.0f
#define FRACTONICA_GLYPH_FONT_GRID_SIZE 8.0f
#define FRACTONICA_GLYPH_FONT_PADDING_CELLS 2.0f
#define FRACTONICA_GLYPH_FONT_LEGACY_OUTER_DEPTH 6u
#define FRACTONICA_GLYPH_FONT_LEGACY_OUTER_POINT_COUNT 12u
#define FRACTONICA_GLYPH_FONT_LEGACY_HOLE_DEPTH 6u
#define FRACTONICA_GLYPH_FONT_LEGACY_HOLE_POINT_COUNT 7u
#define FRACTONICA_GLYPH_FONT_ARM_MAX_POINTS 8u

typedef struct fractonica_glyph_spec_point {
    float x;
    float y;
} fractonica_glyph_spec_point_t;

static const fractonica_glyph_spec_point_t fractonica_glyph_font_legacy_outer[FRACTONICA_GLYPH_FONT_LEGACY_OUTER_POINT_COUNT] = {
    {-8.0f, -41.57f},
    {8.0f, -41.57f},
    {32.0f, -27.71f},
    {40.0f, -13.86f},
    {40.0f, 13.86f},
    {32.0f, 27.71f},
    {8.0f, 41.57f},
    {-8.0f, 41.57f},
    {-32.0f, 27.71f},
    {-40.0f, 13.86f},
    {-40.0f, -13.86f},
    {-32.0f, -27.71f}
};
static const fractonica_glyph_spec_point_t fractonica_glyph_font_legacy_hole[FRACTONICA_GLYPH_FONT_LEGACY_HOLE_POINT_COUNT] = {
    {8.0f, 0.0f},
    {24.0f, 0.0f},
    {24.0f, 13.86f},
    {0.0f, 27.71f},
    {-24.0f, 13.86f},
    {-24.0f, 0.0f},
    {-8.0f, 0.0f}
};
static const uint8_t fractonica_glyph_font_arm_point_counts[FRACTONICA_GLYPH_SPEC_RADIX] = {
    2u, 4u, 5u, 6u, 4u, 6u, 6u, 8u
};
static const fractonica_glyph_spec_point_t fractonica_glyph_font_arms[FRACTONICA_GLYPH_SPEC_RADIX][FRACTONICA_GLYPH_FONT_ARM_MAX_POINTS] = {
    {{-8.0f, 0.0f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-32.0f, 41.57f}, {-16.0f, 41.57f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-8.0f, 96.99f}, {0.0f, 110.85f}, {8.0f, 96.99f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-40.0f, 55.42f}, {-8.0f, 110.85f}, {0.0f, 96.99f}, {-24.0f, 55.42f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {16.0f, 41.57f}, {32.0f, 41.57f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-40.0f, 55.42f}, {40.0f, 55.42f}, {32.0f, 41.57f}, {-16.0f, 41.57f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-8.0f, 138.56f}, {40.0f, 55.42f}, {32.0f, 41.57f}, {8.0f, 83.14f}, {8.0f, 0.0f}, {0.0f, 0.0f}, {0.0f, 0.0f}},
    {{-8.0f, 0.0f}, {-40.0f, 55.42f}, {0.0f, 124.71f}, {40.0f, 55.42f}, {32.0f, 41.57f}, {0.0f, 96.99f}, {-24.0f, 55.42f}, {8.0f, 0.0f}},
};

#endif /* FRACTONICA_EMBEDDED_GLYPH_SPEC_GENERATED_H */
