// Generated by tools/glyph/generate-glyph-artifacts.mjs from contracts/glyph/v1.json and contracts/glyph/fonts/fractonica-hex-v2.json.
// Grammar SHA-256: fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8
// Font SHA-256: b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8
// Combined SHA-256: f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56
// Do not edit by hand.

import CoreGraphics

enum GlyphSpec {
    static let grammarVersion = "1.0.0"
    static let geometryVersion = "2.1.0"
    static let fontID = "fractonica-hex-v2"
    static let fontVersion = "1.0.0"
    static let sourceSHA256 = "f6457d5aa1533a30e0731b70715a5393bb696c317acaeb8c2a5ab0f18ae27a56"
    static let grammarSHA256 = "fe0dbfd7aa3faa6174cf38d1844848b2276f731b102dafb2f3350ffa68c7f7c8"
    static let fontSHA256 = "b67a6132d41a061ee5b33acd6cbe70344cf7f809e6b86a7425d5df76a58ae7d8"
    static let radix = 8
    static let minimumDigits = 3
    static let maximumDigits = 8
    static let defaultDigits = 5
    static let leftStroke: UInt8 = 1
    static let centreStroke: UInt8 = 2
    static let rightStroke: UInt8 = 4
    static let units: CGFloat = 256.0
    static let socketWidth: CGFloat = 16.0
    static let coreRadius: CGFloat = 41.57
    static let insetThickness: CGFloat = 14.0
    static let gridSize: CGFloat = 8.0
    static let paddingCells: CGFloat = 2.0
    static let legacyCoreOuterDepth = 6
    static let legacyCoreHoleDepth = 6

    static let legacyCoreOuter: [GlyphPoint] = [
        GlyphPoint(x: -8.0, y: -41.57),
        GlyphPoint(x: 8.0, y: -41.57),
        GlyphPoint(x: 32.0, y: -27.71),
        GlyphPoint(x: 40.0, y: -13.86),
        GlyphPoint(x: 40.0, y: 13.86),
        GlyphPoint(x: 32.0, y: 27.71),
        GlyphPoint(x: 8.0, y: 41.57),
        GlyphPoint(x: -8.0, y: 41.57),
        GlyphPoint(x: -32.0, y: 27.71),
        GlyphPoint(x: -40.0, y: 13.86),
        GlyphPoint(x: -40.0, y: -13.86),
        GlyphPoint(x: -32.0, y: -27.71),
    ]
    static let legacyCoreHole: [GlyphPoint] = [
        GlyphPoint(x: 8.0, y: 0.0),
        GlyphPoint(x: 24.0, y: 0.0),
        GlyphPoint(x: 24.0, y: 13.86),
        GlyphPoint(x: 0.0, y: 27.71),
        GlyphPoint(x: -24.0, y: 13.86),
        GlyphPoint(x: -24.0, y: 0.0),
        GlyphPoint(x: -8.0, y: 0.0),
    ]
    static let arms: [[GlyphPoint]] = [
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -32.0, y: 41.57),
            GlyphPoint(x: -16.0, y: 41.57),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -8.0, y: 96.99),
            GlyphPoint(x: 0.0, y: 110.85),
            GlyphPoint(x: 8.0, y: 96.99),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -40.0, y: 55.42),
            GlyphPoint(x: -8.0, y: 110.85),
            GlyphPoint(x: 0.0, y: 96.99),
            GlyphPoint(x: -24.0, y: 55.42),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: 16.0, y: 41.57),
            GlyphPoint(x: 32.0, y: 41.57),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -40.0, y: 55.42),
            GlyphPoint(x: 40.0, y: 55.42),
            GlyphPoint(x: 32.0, y: 41.57),
            GlyphPoint(x: -16.0, y: 41.57),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -8.0, y: 138.56),
            GlyphPoint(x: 40.0, y: 55.42),
            GlyphPoint(x: 32.0, y: 41.57),
            GlyphPoint(x: 8.0, y: 83.14),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
        [
            GlyphPoint(x: -8.0, y: 0.0),
            GlyphPoint(x: -40.0, y: 55.42),
            GlyphPoint(x: 0.0, y: 124.71),
            GlyphPoint(x: 40.0, y: 55.42),
            GlyphPoint(x: 32.0, y: 41.57),
            GlyphPoint(x: 0.0, y: 96.99),
            GlyphPoint(x: -24.0, y: 55.42),
            GlyphPoint(x: 8.0, y: 0.0),
        ],
    ]
}
